development:
  adapter: postgresql
  encoding: unicode
  database: library_manager_development
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: library_manager_test
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: library_manager_production
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5432
